### ISSUE TITLE
Homework Week 10

### ISSUE THREAD

**Issue by ptums** [gsgallant/liri-node-app#1]
Hey Greg, I tried running the liri program but it requires the keys.js file. Can you push this file up to the repo?

Thanks

Peter

**Comment by ptums** [comment]
Ah sorry Greg thought you were the Greg from my class haha

**Comment by gsgallant** [comment]
Hi Peter,

No problem.   Two Gregs.  Haha 

Btw, all of us had keys.js in the .gitignore for Twitter keys security reasons.  That was in the HW instructions.  

Greg (Gallant). 😉

**Comment by rfaroul** [comment]
Instead of providing instructions when the user provides no input, I would write a function called startApp that 1. provides instructions and then 2. runs the whatDoesUserWant switch statement. 

why did you use outputString AND console.log?

otherwise, this looks great.

**Comment by gsgallant** [comment]
I used console.log with the colors npm.  I used the function outputstring for writing to the file because colors could not be used in the file.  So that's why I separated them like that.  

Thanks for the comments. 

Greg
